### ISSUE TITLE
--resize_opt center not work

### ISSUE THREAD

**Issue by Cha0sX** [hanzhi713/image-collage-maker#11]
here is the command.
`python3 make_img.py --path ~/Documents/photo/resize --dest_img ~/Documents/photo/20190607_131053.jpg --size 200 --dup 4 --unfair --freq_mul 100.0 --blending alpha --blending_level 0.1 --resize_opt center --out ~/Documents/photo/result_unfair-dup-4-freq-100-alpha-0_1_cen_200.png`
the result is each tile does not crop the center, but stretch to fit the square

**Comment by hanzhi713** [comment]
Should be fixed by de080df. Thanks for pointing it out.

**Comment by hanzhi713** [comment]
By the way, `--dup` option only works with the fair tile usage mode (i.e. without the `--unfair` flag).

**Comment by Cha0sX** [comment]
> 

It works perfectly! 
And I though the `--dup` option is means how many times can a tile be used at most, no matter about fair/unfair, but this feature depends on your implementation. Maybe not a good idea :)
