### ISSUE TITLE
Feature Request:  CSV log of each tile used

### ISSUE THREAD

**Issue by Pizzanomicon** [hanzhi713/image-collage-maker#12]
Would love an option output CSV log of each tile used!

**Comment by hanzhi713** [comment]
2 questions:
1. Do you want the option to be added in CLI or GUI (or both)?
2. In what format? I can give you a list of tile filenames in row-major order.

**Comment by Pizzanomicon** [comment]
1)  Both would be great, though discovered a bug that's preventing my use of the GUI (will log momentarily)
2)  CSV or TXT would be great

Thanks for the prompt response and amazing codebase!

**Comment by hanzhi713** [comment]
The basic implementation is complete. Code is on the csv branch https://github.com/hanzhi713/image-collage-maker/tree/csv

Let me know if there's any problem.

**Comment by Pizzanomicon** [comment]
Looks like the "Save tile info" button logs all of the tiles _loaded_ instead of _used_.  As the tiles loaded are already known by the user, the anticipated csv would list the tiles used in the mosaic.

**Comment by hanzhi713** [comment]
Yeah, you're right. It's negligence on my side. c7f683322bea91f67c70e2861cfb1b3b4b9e1a36 should fix it.

**Comment by Pizzanomicon** [comment]
Works like a dream!  Thank you!
