### ISSUE TITLE
Collage with transparency 

### ISSUE THREAD

**Issue by Aleclock** [hanzhi713/image-collage-maker#16]
Hi,
I'm trying to create a collage with a destination image that contains a transparent area (I have a .png file), but when I load it the transparent area is converted into black area (or white). Is it possible to handle a transparent area where no tiles are added?

[Original (with transparency)](https://ibb.co/wwP2CNc)
[After uploading](https://ibb.co/34PzVhT)

**Comment by hanzhi713** [comment]
Yes, it's possible, but I need to modify my code to support this. I'll do it when I have time. It will probably take a few days.

**Comment by Aleclock** [comment]
It would be great, thanks!

**Comment by Aleclock** [comment]
It would be great, thanks!

**Comment by hanzhi713** [comment]
Basic implementation is complete. The code is on the **transparent** branch (https://github.com/hanzhi713/image-collage-maker/tree/transparent). Just add `--transparent` for your cli command or tick the `transparent masking` checkbox on the GUI to use this function. 

Let me know if it works or not. I'll do more testing and update the readme and examples tomorrow. 

Demo:
![result](https://user-images.githubusercontent.com/21034047/180394067-83265bd0-1d4a-4fa6-9f4a-4e664734bc35.png)

**Comment by hanzhi713** [comment]
I'll just assume your issue is solved. Please reopen it if you find any problems.
