### ISSUE TITLE
[Feature] Multiple output

### ISSUE THREAD

**Issue by Drjacky** [hanzhi713/image-collage-maker#19]
Imagine there are 20 images.
You set the collage to be 2x2
Is it possible to address the folder (that includes all 20 images) and results in 5 collage photos? (each has 4 images on it)

**Comment by hanzhi713** [comment]
Yes, it's possible. You can just create a 10x2 collage and cut it into 5 pieces. If you want a photomosaic, then also concatenate the destination image.

**Comment by hanzhi713** [comment]
I'm extremely busy recently, and I won't be able to provide an implementation. But it is not hard to do, so maybe you can try to implement yourself.

**Comment by hanzhi713** [comment]
Closing the issue. If people really need this feature, I can add to my todo list.
