### ISSUE TITLE
Master Branch Does not Seem to be using GPU in GUI

### ISSUE THREAD

**Issue by Pizzanomicon** [hanzhi713/image-collage-maker#22]
The [Computing Assignments] phase does not seem to be engaging my GPU on the current branch, while the old stale branch of csv utilized the GPU exceptionally well.  I know cupy is running appropriately...

The environment I'm using is:

Name                    Version                   Build  Channel
altgraph                  0.17.3                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2022.10.11           haa95532_0
certifi                   2022.9.24       py310haa95532_0
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.0.4                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cryptography              38.0.1                   pypi_0    pypi
cudatoolkit               11.7.0              ha6f8bbd_10    conda-forge
cupy                      11.2.0          py310h782d1bb_0    conda-forge
fastrlock                 0.8             py310h8a704f9_2    conda-forge
future                    0.18.2                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
lapjv                     1.3.1                    pypi_0    pypi
libffi                    3.4.2                hd77b12b_4
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
numpy                     1.23.4                   pypi_0    pypi
numpy-base                1.23.3          py310h04254f7_0
opencv-contrib-python     4.5.5.62                 pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0
pefile                    2022.5.30                pypi_0    pypi
pip                       22.2.2          py310haa95532_0
pycparser                 2.21                     pypi_0    pypi
pyinstaller               4.8                      pypi_0    pypi
pyinstaller-hooks-contrib 2022.12                  pypi_0    pypi
pyopenssl                 22.0.0                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.6               hbb2ffb3_1
python_abi                3.10                    2_cp310    conda-forge
pywin32-ctypes            0.2.0                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
setuptools                65.5.0          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.3               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tqdm                      4.64.1                   pypi_0    pypi
tzdata                    2022f                h04d1e81_0
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
win-inet-pton             1.1.0                    pypi_0    pypi
wincertstore              0.2             py310haa95532_2
xz                        5.2.6                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0

**Comment by hanzhi713** [comment]
Which mode are you using? Fair or unfair?

**Comment by hanzhi713** [comment]
Upon a closer look, this is indeed a bug and is resolved in 4d542ce3319178fb5a391ee8bdea1b5116b1e837
