### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by Abdull** [hanzhi713/image-collage-maker#23]
Using
* `hanzhi713/image-collage-maker` in version `v5.1`
* on Debian 11 bullseye

```
python3 gui.py
Traceback (most recent call last):
  File "/root/git/image-collage-maker/gui.py", line 1, in <module>
    import tkinter as tk                                 
ModuleNotFoundError: No module named 'tkinter'
```

I was able to fix this problem with installing `python3-tk`:

```
apt install python3-tk
```

I guess this is good to document.

Cheers

**Comment by hanzhi713** [comment]
Thanks for the note. I updated the readme to include this info.
