### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Abdull** [hanzhi713/image-collage-maker#26]
(on latest `ea6c45753122135dc21cfd71b3b3edefe1a70fd2` from `2022-11-26`).

I encountered one more undeclared dependency:

```
ModuleNotFoundError: No module named 'numpy'
```

I solved this issue by installing *numpy* with `pip install numpy`.

Thank you for *image-collage-maker* and keep up the great work!

**Comment by hanzhi713** [comment]
This seems weird. If you install the dependencies with `pip install -r requirements.txt`, it should install numpy, unless numpy is not a dependency of opencv-contrib-python anymore.

**Comment by hanzhi713** [comment]
Ok I see the problem. You need to install the dependencies one-by-one to resolve the issue. 

```bash
cat requirements.txt | xargs -n 1 pip install
```

**Comment by hanzhi713** [comment]
I've updated the readme to reflect this.
