### ISSUE TITLE
UnboundLocalError: local variable 'w' referenced before assignment

### ISSUE THREAD

**Issue by nonspectare** [hanzhi713/image-collage-maker#28]
Hello,

I'm on MacOs 13.4.1/Intel and Python 3.8.0. pip'ed requirements.txt and run gui.py. The Gui is opening and I can select an image folder. After clicking on "choose" while processing, the error "UnboundLocalError: local variable 'w' referenced before assignment" appears.

Thanks

**Comment by hanzhi713** [comment]
Might be fixed by dd17f1a2904b88d7218bfcb3128383ac2c422183. This is indeed a bug.

Please pull from master branch and try running gui.py again. Let me know if the issue still persists.

**Comment by s-schmitz** [comment]
> @nonspectare Might be fixed by [dd17f1a](https://github.com/hanzhi713/image-collage-maker/commit/dd17f1a2904b88d7218bfcb3128383ac2c422183). This is indeed a bug.
> 
> Please pull from master branch and try running gui.py again. Let me know if the issue still persists.

Now its works. Thank you very much 👍
