### ISSUE TITLE
flag for number of images in width and height

### ISSUE THREAD

**Issue by ak9250** [hanzhi713/image-collage-maker#6]
I have a 100 images I ran this command

!python3 make_img.py --path /inpath --out /outpath/collage.jpg --sort pca_bgr --size 200

looking to get a 2000x2000px image

I got a 2600x1400px image which is collage and it has 13 images across and height of 7 images so possible some images not there.

How can I get 2000x2000px collage image with 100 images input and 10 images across width and 10 images height?

**Comment by hanzhi713** [comment]
Try this:
`python3 make_img.py --path /inpath --out /outpath/collage.jpg --sort pca_bgr --size 200 --ratio 1 1`
The `ratio` option sets the aspect ratio of your collage.

**Comment by hanzhi713** [comment]
Issue no longer active. Closed.
