### ISSUE TITLE
Black screen!

### ISSUE THREAD

**Issue by Drjacky** [hanzhi713/image-collage-maker#8]
v3.3
<img width="1003" alt="Screen Shot 2022-01-16 at 12 11 02" src="https://user-images.githubusercontent.com/2296754/149659404-32c69dab-5d14-4736-af98-204f80c36680.png">

**Comment by Drjacky** [comment]
```python
➜  NFT ./photomosaic-maker-3.3-macos-x64
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```

**Comment by hanzhi713** [comment]
Interesting. The macOS version is not really tested as I don't own a Mac machine. I'll investigate this.

**Comment by Drjacky** [comment]
@hanzhi713 I can try your pre-releases on the Mac if you want. Just attach them here and I'll send the result.

**Comment by hanzhi713** [comment]
It seems that the Tkinter that comes with macOS has some serious problems. My app is built with Python 3.7 and it will use the system supplied Tkinter. Give me a day or two and let me try with Python 3.9 build and see if it works.

**Comment by hanzhi713** [comment]
Try this Python 3.9 build: https://github.com/hanzhi713/image-collage-maker/releases/tag/v3.4

**Comment by Drjacky** [comment]
This one: [photomosaic-maker-3.4-macos-x64.3-macos-x64](https://github.com/hanzhi713/image-collage-maker/releases/download/v3.4/photomosaic-maker-3.4-macos-x64.3-macos-x64)

resulted this ->
```python
./photomosaic-maker-3.4-macos-x64.3-macos-x64
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```
<img width="1001" alt="Screen Shot 2022-01-21 at 09 58 53" src="https://user-images.githubusercontent.com/2296754/150506860-356fa4b6-f5ca-48bc-847c-0ed60ff289f6.png">
_______
Any option/flag we could add to see the stack trace for debugging purposes?

**Comment by hanzhi713** [comment]
> Any option/flag we could add to see the stack trace for debugging purposes?
The terminal should show stack trace if there's any

**Comment by Drjacky** [comment]
Then no, the only log was that `DEPRECATION WARNING`

**Comment by hanzhi713** [comment]
Can you try the macos 11 build? https://github.com/hanzhi713/image-collage-maker/releases/tag/v3.4-macos11

**Comment by Drjacky** [comment]
When the app opened, it was black, then when I dragged the window:
<img width="500" alt="Screen Shot 2022-01-26 at 16 32 13" src="https://user-images.githubusercontent.com/2296754/151205127-69c352de-0610-4d32-9592-1c9d644761b3.png">
Then, when you leave it for a few seconds and switch to another desktop and back, it blinks between the black screen and the app UI screen quickly:

![Screen Recording 2022-01-26 at 16 35 23](https://user-images.githubusercontent.com/2296754/151208192-7d373d93-b3f3-4d6c-b0aa-73106b02eeff.gif)

**Comment by hanzhi713** [comment]
Ok. Let me see if I can borrow a MacBook running macos 12 to reproduce this.

**Comment by ncarboni** [comment]
I have the same problem running photomosaic-maker-4.2-macos-11-x64 on Mac 12.3 (M1 Chip)
<img width="1118" alt="photomosaic" src="https://user-images.githubusercontent.com/5669838/173926793-01a5972e-4d99-4a7e-bd02-428558546213.png">


Any solution? I also have problem installing lapjv on M1, so I was hoping to use at least the binaries

**Comment by hanzhi713** [comment]
Unfortunately, my binaries only support x86-64 architecture. M1 is on ARM64 I believe.

**Comment by hanzhi713** [comment]
> Any solution? I also have problem installing lapjv on M1, so I was hoping to use at least the binaries

If you compile from source, lapjv can work. The lapjv binaries also assume x64 architecture.

**Comment by Drjacky** [comment]
@hanzhi713 https://github.com/actions/virtual-environments/issues/5446

**Comment by hanzhi713** [comment]
> 

This will be helpful, but it's not for M1. Still, I can try to start providing macOS 12 builds.

**Comment by ncarboni** [comment]
Thank you, however lapjv doesn't seems to be support to be built on m1 either... :/
In any case,  if in the future you would like to build it for M1, there are some AWS instances (but definitively not free) https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-ec2-m1-mac-instances-macos/ Thank you for the help!
