### ISSUE TITLE
def limit_wh(w: int, h: int, max_width: int, max_height: int):

### ISSUE THREAD

**Issue by Drjacky** [hanzhi713/image-collage-maker#9]
```python
Successfully installed altgraph-0.17.2 lapjv-1.3.1 macholib-1.15.2 opencv-contrib-python-4.5.3.56 pyinstaller-4.6 pyinstaller-hooks-contrib-2021.5 tqdm-4.62.3
➜  image-collage-maker git:(master) python gui.py
  File "gui.py", line 20
    def limit_wh(w: int, h: int, max_width: int, max_height: int):
                  ^
SyntaxError: invalid syntax
```

**Comment by hanzhi713** [comment]
Hey, you need Python v3.6 or newer for this to work.

**Comment by Drjacky** [comment]
Python 3.9.9

```python
➜  image-collage-maker git:(master) python3 gui.py
Traceback (most recent call last):
  File "image-collage-maker/gui.py", line 14, in <module>
    import cv2
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.9/site-packages/cv2/cv2.cpython-39-darwin.so)
```

**Comment by Drjacky** [comment]
I fixed the error by uninstalling the opencv-python, then run `!pip install "opencv-python-headless<4.3"`.
Now, it shows this error:
```python
➜  image-collage-maker git:(master) python3 make_img.py --path ImagesAll --recursive --resize_opt stretch --sort rand
[Reading files]: 100%|████████████| 144971/144971 [00:00<00:00, 245103.27file/s]
Read 0 images
Traceback (most recent call last):
  File "image-collage-maker/make_img.py", line 795, in <module>
    main(parser.parse_args())
  File "image-collage-maker/make_img.py", line 740, in main
    grid, sorted_imgs = sort_collage(imgs, args.ratio, args.sort, args.rev_sort)
  File "image-collage-maker/make_img.py", line 248, in sort_collage
    grid = calc_grid_size(ratio[0], ratio[1], num_imgs)
  File "image-collage-maker/make_img.py", line 187, in calc_grid_size
    return min(possible_wh, key=lambda x: ((x[0] / x[1]) - (rw / rh)) ** 2)
ValueError: min() arg is an empty sequence
```

**Comment by hanzhi713** [comment]
It seems that although there are a lot of files in your image path, none of them are readable/decodable. That's why you see
```
Read 0 images
```

In what formats are your images stored?

**Comment by hanzhi713** [comment]
> Python 3.9.9
> 
> ```python
> ➜  image-collage-maker git:(master) python3 gui.py
> Traceback (most recent call last):
>   File "image-collage-maker/gui.py", line 14, in <module>
>     import cv2
>   File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 9, in <module>
>     from .cv2 import _registerMatType
> ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.9/site-packages/cv2/cv2.cpython-39-darwin.so)
> ```

Does gui.py work now after your fix?

**Comment by Drjacky** [comment]
No, after I fixed the issue by running this command: `!pip install "opencv-python-headless<4.3"`, I get the error I mentioned above (https://github.com/hanzhi713/image-collage-maker/issues/9#issuecomment-1016284741).

**Comment by hanzhi713** [comment]
Are you running in a headless environment?

**Comment by Drjacky** [comment]
No

**Comment by Drjacky** [comment]
The issue has been solved with the new requirements you put.

```python
➜  image-collage-maker git:(master) pip3 install -r requirements.txt
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting opencv-contrib-python==4.5.5.62
  Downloading opencv_contrib_python-4.5.5.62-cp36-abi3-macosx_10_15_x86_64.whl (54.8 MB)
     |████████████████████████████████| 54.8 MB 842 kB/s
Requirement already satisfied: lapjv==1.3.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.3.1)
Collecting pyinstaller==4.8
  Downloading pyinstaller-4.8-py3-none-macosx_10_13_universal2.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 25.5 MB/s
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.62.3)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.9/site-packages (from opencv-contrib-python==4.5.5.62->-r requirements.txt (line 1)) (1.21.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (59.0.1)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (2021.5)
Requirement already satisfied: altgraph in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (0.17.2)
Requirement already satisfied: macholib>=1.8 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (1.15.2)
Installing collected packages: pyinstaller, opencv-contrib-python
  Attempting uninstall: pyinstaller
    Found existing installation: pyinstaller 4.6
    Uninstalling pyinstaller-4.6:
      Successfully uninstalled pyinstaller-4.6
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.5.3.56
    Uninstalling opencv-contrib-python-4.5.3.56:
      Successfully uninstalled opencv-contrib-python-4.5.3.56
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed opencv-contrib-python-4.5.5.62 pyinstaller-4.8
➜  image-collage-maker git:(master) python3 gui.py
```

**Comment by hanzhi713** [comment]
Can you try `make_img.py` now?

**Comment by hanzhi713** [comment]
> The issue has been solved with the new requirements you put.
> 
> ```python
> ➜  image-collage-maker git:(master) pip3 install -r requirements.txt
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Collecting opencv-contrib-python==4.5.5.62
>   Downloading opencv_contrib_python-4.5.5.62-cp36-abi3-macosx_10_15_x86_64.whl (54.8 MB)
>      |████████████████████████████████| 54.8 MB 842 kB/s
> Requirement already satisfied: lapjv==1.3.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.3.1)
> Collecting pyinstaller==4.8
>   Downloading pyinstaller-4.8-py3-none-macosx_10_13_universal2.whl (1.6 MB)
>      |████████████████████████████████| 1.6 MB 25.5 MB/s
> Requirement already satisfied: tqdm in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.62.3)
> Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.9/site-packages (from opencv-contrib-python==4.5.5.62->-r requirements.txt (line 1)) (1.21.4)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (59.0.1)
> Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (2021.5)
> Requirement already satisfied: altgraph in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (0.17.2)
> Requirement already satisfied: macholib>=1.8 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (1.15.2)
> Installing collected packages: pyinstaller, opencv-contrib-python
>   Attempting uninstall: pyinstaller
>     Found existing installation: pyinstaller 4.6
>     Uninstalling pyinstaller-4.6:
>       Successfully uninstalled pyinstaller-4.6
>   Attempting uninstall: opencv-contrib-python
>     Found existing installation: opencv-contrib-python 4.5.3.56
>     Uninstalling opencv-contrib-python-4.5.3.56:
>       Successfully uninstalled opencv-contrib-python-4.5.3.56
>   DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Successfully installed opencv-contrib-python-4.5.5.62 pyinstaller-4.8
> ➜  image-collage-maker git:(master) python3 gui.py
> ```
> 
> Result:
> 
> <img alt="Screen Shot 2022-01-21 at 10 25 20" width="1004" src="https://user-images.githubusercontent.com/2296754/150511051-83cdab67-78f0-4ddb-bbe6-f07ebc8aaad1.png">
> 
> But the UI is frozen. I cannot interact with the UI!

Not sure why this is the case until I got my hand on a macOS machine

**Comment by Drjacky** [comment]
Yes, this works now: `python3 make_img.py --path /Users/drjacky/ImagesAll --sort rand --size 50 --out /Users/drjacky/outttt.jpg`

But, images need to be at the root of the folder and not in subfolders. Is there any way to support subfolders?

**Comment by hanzhi713** [comment]
`--recursive` flag will do

**Comment by Drjacky** [comment]
Thanks!
And is there any chance we define the width but not the height? So, it won't become a square; I mean we keep the aspect ratio of each picture.

**Comment by hanzhi713** [comment]
It is possible with reasonable effort to support customizable aspect ratios of the tiles. It is just that all of the tiles must have or be resized to the same aspect ratio. This is not supported yet, I do plan to support it sometimes in the future. 

If the tiles have different aspect ratios, we need very different algorithms to arrange the tiles.

**Comment by hanzhi713** [comment]
> The issue has been solved with the new requirements you put.
> 
> ```python
> ➜  image-collage-maker git:(master) pip3 install -r requirements.txt
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Collecting opencv-contrib-python==4.5.5.62
>   Downloading opencv_contrib_python-4.5.5.62-cp36-abi3-macosx_10_15_x86_64.whl (54.8 MB)
>      |████████████████████████████████| 54.8 MB 842 kB/s
> Requirement already satisfied: lapjv==1.3.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.3.1)
> Collecting pyinstaller==4.8
>   Downloading pyinstaller-4.8-py3-none-macosx_10_13_universal2.whl (1.6 MB)
>      |████████████████████████████████| 1.6 MB 25.5 MB/s
> Requirement already satisfied: tqdm in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.62.3)
> Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.9/site-packages (from opencv-contrib-python==4.5.5.62->-r requirements.txt (line 1)) (1.21.4)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (59.0.1)
> Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (2021.5)
> Requirement already satisfied: altgraph in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (0.17.2)
> Requirement already satisfied: macholib>=1.8 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.8->-r requirements.txt (line 3)) (1.15.2)
> Installing collected packages: pyinstaller, opencv-contrib-python
>   Attempting uninstall: pyinstaller
>     Found existing installation: pyinstaller 4.6
>     Uninstalling pyinstaller-4.6:
>       Successfully uninstalled pyinstaller-4.6
>   Attempting uninstall: opencv-contrib-python
>     Found existing installation: opencv-contrib-python 4.5.3.56
>     Uninstalling opencv-contrib-python-4.5.3.56:
>       Successfully uninstalled opencv-contrib-python-4.5.3.56
>   DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Successfully installed opencv-contrib-python-4.5.5.62 pyinstaller-4.8
> ➜  image-collage-maker git:(master) python3 gui.py
> ```
> 
> Result:
> 
> <img alt="Screen Shot 2022-01-21 at 10 25 20" width="1004" src="https://user-images.githubusercontent.com/2296754/150511051-83cdab67-78f0-4ddb-bbe6-f07ebc8aaad1.png">
> 
> But the UI is frozen. I cannot interact with the UI!

It tested gui.py on macOS Big Sur (version 11.6.1) and it worked fine. What's your mac's version?

**Comment by Drjacky** [comment]
12.1 (21C52)

**Comment by hanzhi713** [comment]
> Thanks! And is there any chance we define the width but not the height? So, it won't become a square; I mean we keep the aspect ratio of each picture.

Basic support for non-square tile sizes is implemented in the `nonsquare` branch. https://github.com/hanzhi713/image-collage-maker/tree/nonsquare

Currently, you need to specify both width and height. I will add something like automatic inference of height based on aspect ratio and specified width later.

**Comment by Drjacky** [comment]
I tried that branch but, it crops the image horizontally.

Just to giving you an idea, this project keeps the aspect ratio: https://github.com/delimitry/collage_maker
But, I'm not sure why it loses the quality of each tile.

**Comment by hanzhi713** [comment]
If you want to keep the aspect ratio of individual tiles, unfortunately, this is out of the scope of this project. This project is a photomosaic maker (albeit having simple collage-making functionality) which requires all tiles to have the same aspect ratio. 

To be honest, I should've named the repository as "photomosaic maker".

**Comment by dw61** [comment]
On my computer with the same OS version (12.1), running `brew install python-tk@3.9` resolved the tkinter problem, and I can run `gui.py` smoothly.
